OptiQL再現実装
dbgroup-nagoya-u/cpp-utility pull request #34
Opened 2024-12-23 06:58 UTC by sigu03

再現実装を行いテストが通ったためレビューをお願いします．（Releaseビルドでテスト成功）
コードに稚拙な点が多くあるかと思いますが，よろしくお願いします．

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +end:
```suggestion
```

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +    dest_->UnlockX(qid_, new_ver_);  // 引数変更
```suggestion
    dest_->UnlockX(qid_, new_ver_);
```

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +    dest_->UnlockX(qid_, new_ver_);  // 引数変更
```suggestion
    dest_->UnlockX(qid_, new_ver_);
```

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
ここかなりエクストリームって感じなので何が起こってるか説明してほしいです（必要に応じてそのままコードのコメントとして載せたい）．

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +    lock_.fetch_and(~(kOPReadLock | kVersionMask), kRelaxed);
```suggestion
    // disable opportunistic read
    lock_.fetch_and(~(kOPReadLock | kVersionMask), kRelaxed);
```

2024-12-23 11:15 UTC, Mackyson commented on src/lock/optiql.cpp
> +/// @brief A bit mask for extracting an X-lock state and version values.
```suggestion
/// @brief A bit mask for extracting a lock state.
```

2024-12-23 11:22 UTC, Mackyson requested changes

2024-12-23 11:22 UTC, Mackyson commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
ここ左辺が`ver`で右辺のマスクが`kLockMask`なので混乱すると思います．

`qnode`の`ver`のMSB（i.e., XLock）を最初に（`qnode`のコンストラクタと`RetainQID`内の`qnode`の初期化時に）立てておけばここのStoreがいらなくなって嬉しい気がしますが，なにか不都合ありますかね？

2024-12-23 12:25 UTC, sigu03 commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
テストにリードに関するものを入れてないのでちゃんと動くかわかりませんが，ロックがないときかロックがあってもオポチュニスティックリードが立っているときにTrueになるようにしています．
もともと`*cur & kXLock) == kNoLocks`だけあり，楽観的読み取り条件が入っていると考えたためこの内容を書いています．正直もっときれいな書き方があるとは思うのですが，いったんかけるだけ書こうと思いこの書き方にしています．
杉浦先生と話したときにオポチュニスティックリード用のビットがなくてもロックを離せばいいという話はしたのですが，再現実装ということでオポチュニスティックリード用のビットを作って操作しています．

2024-12-23 12:56 UTC, Mackyson commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
これ下側はどういうときに立つんでしょうか．

2024-12-23 13:05 UTC, sigu03 commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
qnodeの中身は空っぽでスタートさせると考えていたのでこの書き方になっていますが，qnode初期化時にverのXLockを立ててしまって問題なさそうには見えます．

2024-12-23 13:08 UTC, sigu03 commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
一応そういうイメージなんですけどオポチュニスティックリードが立っているときは必ずロックがかかっているので，オポチュニスティックリードが立っているかどうかだけ分かればいいのですがうまい表現がすぐに思いつかなかったのでこの書き方になってます．

2024-12-23 13:29 UTC, Mackyson commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
これでどうです？

```suggestion
        return (*cur & kXLock) == kNoLocks  // Lock released
               || (*cur & kOPReadLock);     // or, opportunistically readable
```

2024-12-23 13:42 UTC, Mackyson commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
多分大丈夫だと思うんですが，先生にレビュー回したときに確認してみましょうか．

2024-12-24 03:26 UTC, sigu03 commented on src/lock/optiql.cpp
> +                | (((*cur ^ kXLock ^ kOPReadLock) & kLockMask) == kNoLocks));
ありがとうございます．GetVersionにも同じ部分があったので変更しておきました．

2024-12-24 03:32 UTC, sigu03 commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
わかりました．いったん変更入れずにおいておきます．

2024-12-24 03:40 UTC, sigu03 commented
レビューありがとうございます．
qnodeの初期化以外の点について修正を反映しました．
オポチュニスティックリードが関係する部分について追加で変更を入れたので，確認をお願いしたいです．

2024-12-24 04:41 UTC, Mackyson approved these changes
OKです！先生に見てもらってください。

ちなみに、レビューでsuggested changeが来た場合、なんかコミットできそうなボタンが表示されるはずで、それをクリックするするだけで提案変更を反映できます。
コミットが増えるのが嫌なら今回のように1コミットにまとめるのもよいですが、もし知らなかったなら今度使ってみるとよいかも？

2024-12-24 05:01 UTC, sigu03 commented
ありがとうございます．
レビューの反映についてちょっと不安で試すのを躊躇してたのですが，次から試してみます．
先生に見ていただくのはこのプルリクエストのレビュアーに追加すればいいですか．

2024-12-24 05:24 UTC, Mackyson commented
ここに追加すればOKです

2024-12-24 07:19 UTC, sigu03 commented
@baycedar 
 一通り先輩に確認していただいたので，レビューのお願いをさせていただきました．
確認よろしくお願いします．

2024-12-25 02:50 UTC, baycedar requested changes
ざっと見てコメントを入れました．Conversationで桑村君と相談してた部分についてはこちらからもコメントを入れたので，ちょっと確認をお願いします．

2024-12-25 02:50 UTC, baycedar commented on include/dbgroup/lock/optiql.hpp
> +      uint64_t ver);
Doxygenコメントに `ver` 用の `@param` を追加しておいてください．内容は `optimistic_lock.hpp` のものと同じでOKです．

2024-12-25 02:50 UTC, baycedar commented on test/lock/mcs_lock_test.cpp
> +  std::mutex mtx_{};
履歴に何も残っていませんが，これは未使用ですかね？自分が例示した際に追記したものが残っているのであれば，ヘッダのインクルード含めて削除しておいてください．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +constexpr uint64_t kOPReadLock = 1UL << 61UL;
細かいですけど，これって"Lock"ですかね？"Flag"とかでいい気が．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +               || (*cur & kOPReadLock);     // or, opportunistically readable
```cpp
constexpr uint64_t kXAndOPReadMask = kXLock | kOPReadLock;
```

みたいなのを作って，

```suggestion
        return (*cur & kXAndOPReadMask) != kXLock;
```

とした方がシンプルでよい気がします．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
これは一旦このままで．排他ロックのみを想定する場合は最初からフラグを立てておけばよいのですが，共有ロック（場合によってはSIX）にも拡張する予定なので，1つ前のスレッドが何のロックを握っていたのか把握する必要があります…

…まで書いたんですが，やっぱりいらないですかね？MCSロックの場合は共有ロックカウンタがいくつだったのかを厳密に保持しておく必要がありました[^1]が，OptiQLでは論文に書いてもらったとおり共有ロックを握るのは1スレッドだけなので，単に自身がX/S/SIXいずれかなのかを自身のキューノードに入れておけば十分（

1. 先行スレッドは `next` で次のノードを読む，
2. 次ノード内の `ver` を読んで次に取得されるロックの種類を判別する，
3. 共有領域（ `lock_` ）のロック状態のバージョンを更新しつつ，次に取得されるロックフラグを同時に埋め込む，
4. 次ノード内の `ver` を更新しロックを受け渡す

）な気がしてきました．どう思います？

[^1]: https://github.com/dbgroup-nagoya-u/cpp-utility/blob/main/design_doc/lock.md#class-mcslock

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +  auto pred_qid = (cur & kQIDMask) >> kQIDShift;
```suggestion
  const auto pred_qid = (cur & kQIDMask) >> kQIDShift;
```

もしくは，この次の行でしか使わないので直に値を埋め込んでもよいです．変数名が `pred_node` な時点で意図はほぼ伝わりますし．

また， `pred_node` 自体もelseで分岐した先でしか使わないので，ここではなく分岐した後に作成しましょうか．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +    qnode->ver.store((cur & kVersionMask) + kVersionUpdate, kRelease);
よく見るとこの分岐は不要ですね．以前口頭で伝えたとおりバージョン管理はユーザ側に投げるので， `QNode::ver` はロック状態の受け渡しにしか使いません．

そう考えると，そもそも `QNode::ver` という名前自体が紛らわしいですね．前述のcoversationの内容が正しいという前提でですが， `QNode::lock` とかに名前を変えて型も `std::atomic_bool` にしてしまっていい気がしてきました．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +      std::this_thread::yield();
これ自分も書き方がそのときどきでぶれちゃんですが， `yield` を呼び出している時点でなところはあるのでspinlock hintの方は削除でOKです．

```suggestion
      std::this_thread::yield();
```

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +    lock_.fetch_and(~(kOPReadLock | kVersionMask), kRelaxed);
フラグを下ろすだけなら XOR で十分ですね．また，このタイミングで先行スレッドの書いたバージョン値を読む必要があるのと，フェンスを貼るタイミングはこっちですね．

```suggestion
    cur = lock_.fetch_xor(kOPReadLock, kAcquire);
```

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +  lock_.fetch_or(kOPReadLock | ver, kRelaxed);
他のスレッドに変更内容を読ませる必要があるので，ここはフェンスがいります．

```suggestion
  lock_.fetch_or(kOPReadLock | ver, kRelease);
```

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +  next_ptr->ver.store(ver + kVersionUpdate, kRelease);
前述のコメントの波及でそもそもが変わりそうですが，ここもバージョンの値は意味を持たないので，ロックフラグの立っていない適当な値を渡せばOKです．また，OptiQLにおいてフェンスは共有領域（ `lock_` ）を起点に設定すれば十分なので，こっちはフェンスなしでOKです．

```suggestion
  next_ptr->ver.store(kNoLocks, kRelaxed);
```

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +        return (*cur & kXLock) == kNoLocks  // lock released
同上（最初の方のコメント）．

2024-12-25 02:50 UTC, baycedar commented on src/lock/optiql.cpp
> +    while (qnode->ver.load(kAcquire) & kLockMask) {
見逃してましたが，ここもフェンスは不要です．

```suggestion
    while (qnode->ver.load(kRelaxed) & kLockMask) {
```

2024-12-25 04:00 UTC, sigu03 commented
ありがとうございます．
確認と修正をしておきます．

2024-12-25 04:03 UTC, sigu03 commented on test/lock/mcs_lock_test.cpp
> +  std::mutex mtx_{};
わかりました．戻しておきます．

2024-12-25 05:24 UTC, sigu03 commented on src/lock/optiql.cpp
> +  auto pred_qid = (cur & kQIDMask) >> kQIDShift;
いったん直に値を埋め込む形で調整してみます

2024-12-25 05:25 UTC, sigu03 commented on src/lock/optiql.cpp
> +constexpr uint64_t kOPReadLock = 1UL << 61UL;
表記をLockからFlagに変更してみます．

2024-12-25 05:48 UTC, sigu03 commented on src/lock/optiql.cpp
> +    qnode->ver.store((cur & kVersionMask) + kVersionUpdate, kRelease);
いったんロックがとられていない状況の処理だけ消すように修正しておきます．

2024-12-25 06:40 UTC, sigu03 commented on include/dbgroup/lock/optiql.hpp
> +      uint64_t ver);
いちおうやってみたんですが，追加できてるかいまいちわかんないんですけどできているでしょうか．

2024-12-25 06:42 UTC, sigu03 commented
いったんqnodeの初期化以外の部分の修正をしました．

2024-12-25 06:56 UTC, baycedar commented on include/dbgroup/lock/optiql.hpp
> +      uint64_t ver);
はい、これでOKです。

2024-12-25 07:18 UTC, sigu03 commented on include/dbgroup/lock/optiql.hpp
> +      uint64_t ver);
確認ありがとうございます．

2024-12-25 10:19 UTC, sigu03 commented
qnodeの構造と初期化に関する部分以外の修正が終わっているため，一度レビューをお願いしたいと思います．
qnodeの初期化などの部分については具体的な初期化と動作がイメージできていないため，先輩にも確認していただきたいです．

2024-12-25 12:23 UTC, sigu03 commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
実装上では提案していただいたように初期化時にverにXLockをたてて，ストアを消すことになりますか．

2024-12-25 14:49 UTC, Mackyson commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
> 共有ロック（場合によってはSIX）にも拡張する予定

> 共有ロックを握るのは1スレッドだけ

さっき原稿読みました（先に読むべきでした，すみません！），リーダのうち1人がS-Lockを差してOPRead用の時間を作るわけですね．

S-Lockが真面目にキューに並んだら意味ないので，先頭に割り込むことになりますよね？となると，"次のノード"が上記2~4の間で急に変わるんじゃないでしょうか？

2024-12-26 01:34 UTC, baycedar commented on src/lock/optiql.cpp
> +    qnode->ver.store(cur & kLockMask, kRelaxed);
> S-Lockが真面目にキューに並んだら意味ない

そこはreadを優先するかwriteを優先するかですね．共有領域（ `lock_` ）で共有ロックを管理する場合，

> 先頭に割り込むことになります

ので，各排他ロックの間に共有ロックが割り込む形になりこれはread優先です．一方で，一度共有ロックを取ったら他の楽観的読取りも成功するでしょと期待するのであれば，共有ロックもキューノードとしてちゃんと並べて排他ロックが取得される機会を増やしてあげることも考えられます（最初に想定していたのはこっちです）．

とりあえず今回のPR用の結論を言うと，ひとまず最初からフラグを初期化しておく方でOKです．理由は2つで，

1. 上記の共有ロック拡張はもう別のクラス（ `OMCS` みたいなの）で管理したほうがよい，および
2. 共有ロックをキューに並べようと並べまいと共有領域（ `lock_` ）で共有ロックの存在自体は伝えないといけない

ためです（後者の詳細は細かい話なのでちょっと省略します）．一旦これ想定で追加のレビューも返します．＞阿井君

---

ちなみに，提示してもらったコードに関しては後者の想定です．共有ロックは1つ，他のスレッドは楽観的読取り想定なので， `LockS` のAPIは用意せず `PrepareRead` みたいな複合ロック用のAPIのみ公開する予定でいます．

2024-12-26 01:59 UTC, baycedar approved these changes
詳細はconversationの方で述べたとおりです．一旦動作確認をしてもらって，問題なければmainにマージしてください．

2024-12-26 01:59 UTC, baycedar commented on src/lock/optiql.cpp
> +  qnode->ver.store(kNoLocks, kRelaxed);
`QNode` の構成要素ですが，

```cpp
struct QNode {
  /// @brief The next queue node if exist.
  std::atomic<QNode *> next;

  /// @brief A flag for indicating this node's owner holds a lock.
  std::atomic_bool hold_lock;
};
```

としてください．これで初期状態（ゼロ埋め状態）でロックを握っていない状態になります．ここの返却時の初期化も

```suggestion
  qnode->next.store(nullptr, kRelaxed);
  qnode->hold_lock.store(false, kRelaxed);
```

ですね．

2024-12-26 01:59 UTC, baycedar commented on src/lock/optiql.cpp
> +    if (lock_.compare_exchange_weak(cur, new_tail, kAcqRel, kRelaxed)) break;
フェンスもlfenceのみで．

```suggestion
    if (lock_.compare_exchange_weak(cur, new_tail, kAcquire, kRelaxed)) break;
```

2024-12-26 01:59 UTC, baycedar commented on src/lock/optiql.cpp
> +    while (qnode->ver.load(kRelaxed) & kLockMask) {
フラグをatomicに立てるだけでよくなったので，こちらもフェンスは不要になります．

```suggestion
    pred_qnode->next.store(qnode, kRelaxed);
    while (!qnode->hold_lock.load(kRelaxed)) {
```

2024-12-26 01:59 UTC, baycedar commented on src/lock/optiql.cpp
> +  next_ptr->ver.store(kNoLocks, kRelaxed);
同上．

```suggestion
    next_ptr = qnode->next.load(kRelaxed);
    if (next_ptr) break;
    CPP_UTILITY_SPINLOCK_HINT
  }

  next_ptr->hold_lock.store(true, kRelaxed);
```

2024-12-26 02:06 UTC, baycedar approved these changes
すみません1個見逃してました．こちらの変更も反映＆確認してからマージをお願いします．

2024-12-26 02:06 UTC, baycedar commented on src/lock/optiql.cpp
>        &lock_, &cur);
今更になって気づきましたが，よく考えるとここはback off挟んじゃダメでした．Opportunistic readできる期間はキャッシュミス2回分くらいしかないので，読取り側がback offしてるとたぶん（本来成功できるケースでも）ほぼ成功しなくなってしまいます．

なので，yieldで他のスレッドにコアの利用機会を提供しながら待ちましょう．

```cpp
while (true) {
  cur = lock_.load(kAcquire);
  if ((cur & kXAndOPReadMask) != kXLock) break;  // lock released or opportunistically readable
  std::this_thread::yield();
}
```

2024-12-26 02:27 UTC, sigu03 commented
レビューありがとうございます．
わかりました，修正と動作確認をしておきます．
マージ先はadd-optiqlでなくてmainで大丈夫ですか．

2024-12-26 02:54 UTC, baycedar commented
おっとマージ先を見逃してました．QptiQLに関する実装はこれで完了ですよね？であれば一旦add-optiqlにマージしてもらって，再度main宛にPRを出してください．

2024-12-26 03:18 UTC, sigu03 commented on src/lock/optiql.cpp
>        &lock_, &cur);
`auto
OptiQL::OptGuard::VerifyVersion()`
の方のback offは差し替えなくて大丈夫ですか．

2024-12-26 03:20 UTC, sigu03 commented
わかりました．修正が終わった後再度mainへのPRをしておきます．
このときはPRをだしてそのままマージ作業して大丈夫ですか．

2024-12-26 03:26 UTC, baycedar commented on src/lock/optiql.cpp
>        &lock_, &cur);
そちらも同じくback offなしでお願いします．

2024-12-26 03:27 UTC, baycedar commented
いえ，このリポジトリはbranch protection ruleがあるので，自分がapproveを出さないとマージできないはずです．出してもらったら再度全体を確認して，問題なければそのままapproveを出します．

2024-12-26 03:53 UTC, sigu03 commented on src/lock/optiql.cpp
>        &lock_, &cur);
VerifyVersionの方はこんな感じの変更で合っているでしょうか．
```
while (true) {
    cur = dest_->lock_.load(kAcquire);
    if ((cur & kXAndOPReadMask) != kXLock) break;  // lock released or opportunistically readable
    std::this_thread::yield();
}
```

2024-12-26 04:01 UTC, baycedar commented on src/lock/optiql.cpp
>        &lock_, &cur);
いえ，こっちはsfenceが必要なので，別途明示してあげてください．

```cpp
while (true) {
    std::atomic_thread_fence(kRelease);
    cur = dest_->lock_.load(kRelaxed);
    if ((cur & kXAndOPReadMask) != kXLock) break;  // lock released or opportunistically readable
    std::this_thread::yield();
}
```

2024-12-26 04:41 UTC, sigu03 commented on src/lock/optiql.cpp
>        &lock_, &cur);
わかりました．ありがとうございます．

2024-12-26 04:42 UTC, sigu03 commented
修正と動作確認ができたのでマージしておきます．

2024-12-26 04:42 UTC, merged