add pessimistic lock using atomic variable
dbgroup-nagoya-u/cpp-utility pull request #6
Opened 2022-06-30 05:42 UTC by nrkt

2022-06-30 05:45 UTC, nrkt commented
お手隙の際にレビューをよろしくお願いします！

2022-06-30 06:13 UTC, baycedar requested changes
フェンスの貼り方についてコメント入れたので，`UnlockShared`，`Lock`，`Unlock`についても同様に修正してみてもらえますか？

また，ディレクトリ構成については`include/lock/pessimistic_lock.hpp`くらいにしておきましょうか．あとから`optimistic_lock.hpp`も追加すると思うので．

2022-06-30 06:13 UTC, baycedar commented on include/lock.hpp
> +  PessimisticLock(){};
一応明示しておきましょう．

```suggestion
  constexpr PessimisticLock() = default;

  PessimisticLock(const PessimisticLock&) = delete;
  PessimisticLock(PessimisticLock&&) = delete;

  auto operator=(const PessimisticLock&) -> PessimisticLock& = delete;
  auto operator=(PessimisticLock&&) -> PessimisticLock& = delete;
```

2022-06-30 06:13 UTC, baycedar commented on include/lock.hpp
> +    }
ロックを取得したり解放したりするときは競合するメモリ領域へアクセスするときなので，フェンスを細かく指定してあげる必要があると思います．ここだと，

1. 最初の`expected`を用意する時点でacquireフェンスを張って，それまでの他スレッドの書込みを見えるようにする．
2. CASが成功した場合（i.e., 共有ロックを取得できた場合）は，この処理ではロック以外の領域に副作用がないのでフェンスなしでよい．
3. CASが失敗した場合は他のスレッドによって値が書き換えられている可能性があるので，再度acquireフェンスを張って現在値を読み取る．

というふうにフェンスの設置が必要です．たぶん．

```suggestion
    auto expected = lock_.load(std::memory_order_acquire) & (~1UL);  // turn-off LSB
    auto desired = expected + 2;   // increment read-counter
    while (!lock_.compare_exchange_strong(expected, desired, std::memory_order_relaxed, std::memory_order_acquire)) {
      expected = expected & (~1UL);
      desired = expected + 2;
      SPINLOCK_HINT
    }
```

また，代入や読取りでも基本的に`load`や`store`命令を使ってフェンスを明示した方がよいです．使わない場合は全て`std::memory_order_seq_cst`が使われるので．

あと，ビット演算は扱いが色々と怖いので，64bitであることを明示（i.e., `1UL`）してます．

2022-06-30 17:04 UTC, nrkt commented
レビューありがとうございます！
一通り修正しましたので再度レビューをよろしくお願いします！

2022-07-01 01:48 UTC, baycedar approved these changes
ざっとフェンスまわりを修正しました．たぶんこんな感じでいいはず（自信は少しないです）．

たぶんインデントがずれてしまっているので，フォーマッタを掛け直したらマージしてもらえますか？その後，簡単にロック用の単体テストを組んでみてください．ロックを使ってマルチスレッドでカウンタを増加させるくらいのものでよいと思います．

2022-07-01 01:48 UTC, baycedar commented on include/lock/pessimistic_lock.hpp
> +    }
めっちゃややこしいんですが，ここのフェンス設定はたぶんこうです．共有ロックが取得されている以上他のスレッドによってロックの有効領域を変更される可能性がない＆自身もmutex用のワード以外変更しないなので，ここはフェンスなしでも一貫性が保証されます．

```suggestion
    auto expected = lock_.load(std::memory_order_relaxed) & (~1UL);  // turn-off LSB
    auto desired = expected - 2;                                     // decrement read-counter
    while (!lock_.compare_exchange_weak(expected, desired, std::memory_order_relaxed)) {
      desired = expected - 2;
      SPINLOCK_HINT
    }
```

また，共有ロックを取っている以上排他ロックが取得されることはないので，78行目は不要ですね．

2022-07-01 01:48 UTC, baycedar commented on include/lock/pessimistic_lock.hpp
> +    }
ここはこうですね．埋め込むときにacquireとreleaseフェンスを両方埋め込んで，前後の読み書きに対する順序一貫性を保証してあげる必要があると思います．一方で，そっちで順序を保証するのでリトライ時はフェンスなしでOKです．

```suggestion
    uint64_t expected = 0;
    const uint64_t desired = 1;
    while (!lock_.compare_exchange_weak(expected, desired, std::memory_order_acq_rel,
                                          std::memory_order_relaxed)) {
      expected = 0;
      SPINLOCK_HINT
    }
```

2022-07-01 01:48 UTC, baycedar commented on include/lock/pessimistic_lock.hpp
> +                                          std::memory_order_acquire)) {
見逃してましたが，リトライが発生しうるCASは基本`weak`でよいです．逆に，リトライなしの1回だけのときに`strong`を使います．

あと，他のところを直してたらここはこっちのフェンスの方がよい気がしてきました．比較が成功したときにだけ（i.e., ロックが取得できたときだけ）フェンスをはれれば十分なので．

```suggestion
    auto expected = lock_.load(std::memory_order_relaxed) & (~1UL);  // turn-off LSB
    auto desired = expected + 2;                                     // increment read-counter
    while (!lock_.compare_exchange_weak(expected, desired, std::memory_order_acquire,
                                          std::memory_order_relaxed)) {
```

2022-07-01 01:48 UTC, baycedar commented on include/lock/pessimistic_lock.hpp
> +    lock_ = 0;
ここはreleaseフェンスで十分ですね．

```suggestion
    lock_.store(0, std::memory_order_release);
```

2022-07-01 17:50 UTC, merged