Add pessimistic lock test
dbgroup-nagoya-u/cpp-utility pull request #7
Opened 2022-07-01 18:34 UTC by nrkt

2022-07-01 18:37 UTC, nrkt commented
かなり雑ですが，ロックの単体テストを追加しました．
お手隙の際にレビューをよろしくお願いします！

2022-07-03 13:06 UTC, baycedar requested changes
タイムアウト付きのテストのサンプルを考えたので，ちょっと面倒ですがこっちの方針で実装してみてもらえますか？実際にブロックされることを確認しておいた方が安心できるので．

2022-07-03 13:06 UTC, baycedar commented on test/lock/pessimistic_lock_test.cpp
> +  void
ロックについては，実際にブロックが行われるか確認しておいた方がよいと思います．以下はざっと書いてみたサンプルで，`lock_.Lock()`実行後に`VerifyLockShared(kExpectFailed)`みたいに呼び出す想定です（`constexpr bool kExpectFailed = false`）．別スレッドでロックを取りに行って，1ms経ってもロックが取れなければ失敗とみなします．

```suggestion
  void
  VerifyLockShared(const bool expect_success)
  {
    // try to get a shared lock by another thread
    auto lock_shared = [this] (std::promise<void> p) {
      lock_.LockShared();
      p.set_value();
    };
    std::promise<void> p{};
    auto&& f = p.get_future();
    std::thread t{lock_shared, std::move(p)};

    // after one millisecond has passed, give up on acquiring the lock
    const auto rc = f.wait_for(std::chrono::milliseconds{1});

    // verify status to check locking is succeeded
    if (expect_success) {
      ASSERT_EQ(rc, std::future_status::ready);
    } else {
      ASSERT_EQ(rc, std::future_status::timeout);
      lock_.UnLock();  // unlock to join the thread
    }
    t.join();
  }

  void
```

面倒なのは最後の`lock_.UnLock()`で，立ち上げたスレッドを回収するためにロックを外す必要があります．排他ロックの方を試すときは`std::atomic_size_t s_lock_count`で現在の共有ロック（排他ロックも？）の数を把握しておいて，whileか何かですべての共有ロックを解放するまでループを回す必要があると思います．

2022-07-03 13:06 UTC, baycedar commented on include/lock/pessimistic_lock.hpp
> +  }
これについてはできれば実装したくないですね．シングルスレッドのテストなら便利なんですが，マルチスレッド環境だと取得できる値があんまり信用できない（どのタイミングの値か確信を持てない）ので，1個前のコメントみたいにロックが取れるかどうかでテストした方がよいと思います．

2022-07-03 13:06 UTC, baycedar commented on test/lock/pessimistic_lock_test.cpp
> +  }
マルチスレッドのテストは，できれば実際に排他ロックを使ってなにか処理をしたいですね．`size_t counter_{0}`みたいな変数を用意して，それを複数スレッドで各10万回くらい加算するテストを書いてみてもらえますか？イメージとしては，

1. メインスレッドで共有ロックを取得した後，forループで以下の処理を行うスレッドを複数立ち上げる．
    - 排他ロックの取得 > カウンタを1加算 > 排他ロックを解放．
2. メインスレッドで10msくらいsleepして，カウンタがゼロのままなのを確認したら共有ロックを解放．
3. すべてのスレッドをjoinするまで待ち，メインスレッドで共有ロックを取得しカウンタの値を確認．

みたいな感じです．このくらいやっておけばとりあえず安心かなと思います．

2022-07-03 21:42 UTC, nrkt commented on test/lock/pessimistic_lock_test.cpp
> +  void
ありがとうございます！！
(こんな風に実装できるんですね...)

2022-07-04 04:19 UTC, nrkt commented
一通り修正しました！
再度レビューをよろしくお願いします！

2022-07-04 04:29 UTC, baycedar approved these changes
はい，OKです．1点だけ，共有ロックを取ったあとに別スレッドでも共有ロックが取得できることだけテストを組んでもらって，それが終わったらそのままマージしてください．

2022-07-04 05:01 UTC, merged